name       : perl-encode-eucjpascii
version    : 0.03
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Encode-EUCJPASCII-0.03.tar.gz : f998d34d55fd9c82cf910786a0448d1edfa60bf68e2c2306724ca67c629de861
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Encode::EUCJPASCII - eucJP-ascii - An eucJP-open mapping
description: |
    Encode::EUCJPASCII - eucJP-ascii - An eucJP-open mapping
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
